# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Deploy Jekyll with GitHub Pages dependencies preinstalled

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["release"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write
  deployments: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: clone test-deploy-migration-branch-to-workflow
        run: git clone https://github.com/ericherman/test-deploy-migration-branch-to-workflow.git
      - name: checkout gh-pages
        run: |
          cd test-deploy-migration-branch-to-workflow
          git checkout gh-pages
          rm -rf .git
      - name: assemble super-proj gh-pages
        run: |
          mkdir -pv _site
          cp -vR test-deploy-migration-branch-to-workflow _site/
      - name: add landing page
        run: cp -v index.html _site/
      - name: build list files
        run: find ./_site -type f
      - name: Deploy to GitHub Pages
        id: deployment
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
